import type { MetadataRoute } from "next";
import { blogPosts } from "@/lib/blog";
import { SITE_URL } from "@/lib/site";

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  const highPriority = new Set([
    "/blog",
    "/contact",
    "/pricing",
    "/ai",
    "/qa-services-usa",
    "/qa-services-canada",
    "/qa-services-uk",
    "/qa-services-australia",
    "/qa-services-europe",
    "/qa-services-germany",
    "/qa-services-new-york",
    "/qa-services-san-francisco",
    "/qa-services-toronto",
    "/qa-services-london",
    "/remote-qa-services",
    "/qa-outsourcing",
    "/playwright-testing-company",
    "/software-testing-services",
    "/software-quality-assurance",
    "/quality-assurance-services",
    "/sqa-services",
    "/quality-control-testing",
    "/qa-qc-services",
    "/regression-testing-services",
    "/automation-testing-services",
    "/mobile-app-testing",
    "/ai-qa-testing",
    "/software-qa-services",
    "/saas-testing-services",
    "/ecommerce-testing-services",
    "/functional-testing-services",
    "/end-to-end-testing",
    "/smoke-testing-services",
    "/uat-testing-services",
    "/api-testing-services",
    "/performance-testing-services",
    "/load-testing-services",
    "/selenium-testing-services",
    "/cypress-testing-services",
    "/continuous-testing-services",
    "/accessibility-testing-services",
    "/manual-testing-services",
    "/web-application-testing",
    "/website-testing-services",
    "/exploratory-testing-services",
    "/integration-testing-services",
    "/cross-browser-testing",
    "/qa-as-a-service",
    "/dedicated-qa-team",
    "/offshore-qa-testing",
    "/agile-testing-services",
    "/fintech-testing-services",
    "/test-automation-company",
    "/independent-software-testing",
    "/compatibility-testing-services",
    "/usability-testing-services",
    "/chatbot-testing-services",
    "/ios-app-testing",
    "/android-app-testing",
    "/qa-services-austin",
    "/qa-services-seattle",
    "/qa-services-chicago",
    "/qa-services-los-angeles",
    "/qa-services-boston",
    "/qa-services-dallas",
    "/qa-services-denver",
    "/qa-services-miami",
    "/qa-services-vancouver",
    "/qa-services-sydney",
    "/qa-services-melbourne",
    "/qa-services-manchester",
    "/qa-services-berlin",
    "/qa-services-amsterdam",
    "/outsourced-qa",
    "/best-qa-company",
    "/hire-qa-testers",
    "/qa-retainer-vs-hiring",
    "/qa-agency",
    "/software-testing-company",
    "/qa-agency-lahore",
  ]);

  const staticRoutes = [
    "",
    "/services",
    "/services/manual-testing",
    "/services/api-testing",
    "/services/playwright-automation",
    "/services/performance-testing",
    "/ai",
    "/qa-services-usa",
    "/qa-services-canada",
    "/qa-services-uk",
    "/qa-services-australia",
    "/qa-services-europe",
    "/qa-services-germany",
    "/qa-services-new-york",
    "/qa-services-san-francisco",
    "/qa-services-toronto",
    "/qa-services-london",
    "/remote-qa-services",
    "/qa-outsourcing",
    "/playwright-testing-company",
    "/software-testing-services",
    "/software-quality-assurance",
    "/quality-assurance-services",
    "/sqa-services",
    "/quality-control-testing",
    "/qa-qc-services",
    "/regression-testing-services",
    "/automation-testing-services",
    "/mobile-app-testing",
    "/ai-qa-testing",
    "/software-qa-services",
    "/saas-testing-services",
    "/ecommerce-testing-services",
    "/functional-testing-services",
    "/end-to-end-testing",
    "/smoke-testing-services",
    "/uat-testing-services",
    "/api-testing-services",
    "/performance-testing-services",
    "/load-testing-services",
    "/selenium-testing-services",
    "/cypress-testing-services",
    "/continuous-testing-services",
    "/accessibility-testing-services",
    "/manual-testing-services",
    "/web-application-testing",
    "/website-testing-services",
    "/exploratory-testing-services",
    "/integration-testing-services",
    "/cross-browser-testing",
    "/qa-as-a-service",
    "/dedicated-qa-team",
    "/offshore-qa-testing",
    "/agile-testing-services",
    "/fintech-testing-services",
    "/test-automation-company",
    "/independent-software-testing",
    "/compatibility-testing-services",
    "/usability-testing-services",
    "/chatbot-testing-services",
    "/ios-app-testing",
    "/android-app-testing",
    "/qa-services-austin",
    "/qa-services-seattle",
    "/qa-services-chicago",
    "/qa-services-los-angeles",
    "/qa-services-boston",
    "/qa-services-dallas",
    "/qa-services-denver",
    "/qa-services-miami",
    "/qa-services-vancouver",
    "/qa-services-sydney",
    "/qa-services-melbourne",
    "/qa-services-manchester",
    "/qa-services-berlin",
    "/qa-services-amsterdam",
    "/outsourced-qa",
    "/best-qa-company",
    "/hire-qa-testers",
    "/qa-retainer-vs-hiring",
    "/qa-agency",
    "/software-testing-company",
    "/qa-agency-lahore",
    "/pricing",
    "/about",
    "/contact",
    "/become-a-tester",
    "/blog",
    "/faq",
    "/privacy",
    "/terms",
    "/cookies",
  ].map((path) => ({
    url: `${SITE_URL}${path}`,
    lastModified,
    changeFrequency:
      path === "" || path === "/blog" ? ("weekly" as const) : ("monthly" as const),
    priority:
      path === ""
        ? 1
        : highPriority.has(path) || path.startsWith("/services/")
          ? 0.9
          : path === "/services"
            ? 0.85
            : path === "/privacy" || path === "/terms" || path === "/cookies"
              ? 0.3
              : 0.7,
  }));

  const posts = blogPosts.map((post) => ({
    url: `${SITE_URL}/blog/${post.slug}`,
    lastModified: new Date(post.date),
    changeFrequency: "monthly" as const,
    priority: 0.75,
  }));

  return [...staticRoutes, ...posts];
}
